/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CurrentRouteImport } from './routes/current'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as YearsRouteImport } from './routes/years'
import { Route as YouthRouteImport } from './routes/youth'
import { Route as AuctionsIdRouteImport } from './routes/auctions_.$id'
import { Route as DonationsIdRouteImport } from './routes/donations_.$id'
import { Route as ExpensesIdRouteImport } from './routes/expenses_.$id'
import { Route as YearsIndexRouteImport } from './routes/years.index'
import { Route as YearsYearRouteImport } from './routes/years.$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentRoute = CurrentRouteImport.update({
  id: '/current',
  path: '/current',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const YearsRoute = YearsRouteImport.update({
  id: '/years',
  path: '/years',
  getParentRoute: () => rootRouteImport,
} as any)
const YouthRoute = YouthRouteImport.update({
  id: '/youth',
  path: '/youth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/auctions_/$id',
  path: '/auctions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsIdRoute = DonationsIdRouteImport.update({
  id: '/donations_/$id',
  path: '/donations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIdRoute = ExpensesIdRouteImport.update({
  id: '/expenses_/$id',
  path: '/expenses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const YearsIndexRoute = YearsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YearsRoute,
} as any)
const YearsYearRoute = YearsYearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => YearsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/current': typeof CurrentRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/donations': typeof DonationsRoute
  '/expenses': typeof ExpensesRoute
  '/gallery': typeof GalleryRoute
  '/notifications': typeof NotificationsRoute
  '/years': typeof YearsRouteWithChildren
  '/youth': typeof YouthRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/donations/$id': typeof DonationsIdRoute
  '/expenses/$id': typeof ExpensesIdRoute
  '/years/$year': typeof YearsYearRoute
  '/years/': typeof YearsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/current': typeof CurrentRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/donations': typeof DonationsRoute
  '/expenses': typeof ExpensesRoute
  '/gallery': typeof GalleryRoute
  '/notifications': typeof NotificationsRoute
  '/youth': typeof YouthRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/donations/$id': typeof DonationsIdRoute
  '/expenses/$id': typeof ExpensesIdRoute
  '/years/$year': typeof YearsYearRoute
  '/years': typeof YearsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/current': typeof CurrentRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/donations': typeof DonationsRoute
  '/expenses': typeof ExpensesRoute
  '/gallery': typeof GalleryRoute
  '/notifications': typeof NotificationsRoute
  '/years': typeof YearsRouteWithChildren
  '/youth': typeof YouthRoute
  '/auctions_/$id': typeof AuctionsIdRoute
  '/donations_/$id': typeof DonationsIdRoute
  '/expenses_/$id': typeof ExpensesIdRoute
  '/years/$year': typeof YearsYearRoute
  '/years/': typeof YearsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auctions'
    | '/auth'
    | '/current'
    | '/dashboard'
    | '/debug'
    | '/donations'
    | '/expenses'
    | '/gallery'
    | '/notifications'
    | '/years'
    | '/youth'
    | '/auctions/$id'
    | '/donations/$id'
    | '/expenses/$id'
    | '/years/$year'
    | '/years/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auctions'
    | '/auth'
    | '/current'
    | '/dashboard'
    | '/debug'
    | '/donations'
    | '/expenses'
    | '/gallery'
    | '/notifications'
    | '/youth'
    | '/auctions/$id'
    | '/donations/$id'
    | '/expenses/$id'
    | '/years/$year'
    | '/years'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auctions'
    | '/auth'
    | '/current'
    | '/dashboard'
    | '/debug'
    | '/donations'
    | '/expenses'
    | '/gallery'
    | '/notifications'
    | '/years'
    | '/youth'
    | '/auctions_/$id'
    | '/donations_/$id'
    | '/expenses_/$id'
    | '/years/$year'
    | '/years/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuctionsRoute: typeof AuctionsRoute
  AuthRoute: typeof AuthRoute
  CurrentRoute: typeof CurrentRoute
  DashboardRoute: typeof DashboardRoute
  DebugRoute: typeof DebugRoute
  DonationsRoute: typeof DonationsRoute
  ExpensesRoute: typeof ExpensesRoute
  GalleryRoute: typeof GalleryRoute
  NotificationsRoute: typeof NotificationsRoute
  YearsRoute: typeof YearsRouteWithChildren
  YouthRoute: typeof YouthRoute
  AuctionsIdRoute: typeof AuctionsIdRoute
  DonationsIdRoute: typeof DonationsIdRoute
  ExpensesIdRoute: typeof ExpensesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current': {
      id: '/current'
      path: '/current'
      fullPath: '/current'
      preLoaderRoute: typeof CurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/years': {
      id: '/years'
      path: '/years'
      fullPath: '/years'
      preLoaderRoute: typeof YearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youth': {
      id: '/youth'
      path: '/youth'
      fullPath: '/youth'
      preLoaderRoute: typeof YouthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions_/$id': {
      id: '/auctions_/$id'
      path: '/auctions/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations_/$id': {
      id: '/donations_/$id'
      path: '/donations/$id'
      fullPath: '/donations/$id'
      preLoaderRoute: typeof DonationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses_/$id': {
      id: '/expenses_/$id'
      path: '/expenses/$id'
      fullPath: '/expenses/$id'
      preLoaderRoute: typeof ExpensesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/years/': {
      id: '/years/'
      path: '/'
      fullPath: '/years/'
      preLoaderRoute: typeof YearsIndexRouteImport
      parentRoute: typeof YearsRoute
    }
    '/years/$year': {
      id: '/years/$year'
      path: '/$year'
      fullPath: '/years/$year'
      preLoaderRoute: typeof YearsYearRouteImport
      parentRoute: typeof YearsRoute
    }
  }
}

interface YearsRouteChildren {
  YearsYearRoute: typeof YearsYearRoute
  YearsIndexRoute: typeof YearsIndexRoute
}

const YearsRouteChildren: YearsRouteChildren = {
  YearsYearRoute: YearsYearRoute,
  YearsIndexRoute: YearsIndexRoute,
}

const YearsRouteWithChildren = YearsRoute._addFileChildren(YearsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuctionsRoute: AuctionsRoute,
  AuthRoute: AuthRoute,
  CurrentRoute: CurrentRoute,
  DashboardRoute: DashboardRoute,
  DebugRoute: DebugRoute,
  DonationsRoute: DonationsRoute,
  ExpensesRoute: ExpensesRoute,
  GalleryRoute: GalleryRoute,
  NotificationsRoute: NotificationsRoute,
  YearsRoute: YearsRouteWithChildren,
  YouthRoute: YouthRoute,
  AuctionsIdRoute: AuctionsIdRoute,
  DonationsIdRoute: DonationsIdRoute,
  ExpensesIdRoute: ExpensesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
